import type { CustomItem } from '@/types'

export default <CustomItem[]>[
  {
    id: 1,
    name: 'Синяя шапка',
    type: 'hat',
    imageUrl: '/accessories/hat/1.svg',
    price: 0,
  },
  {
    id: 2,
    name: 'Корона',
    type: 'hat',
    imageUrl: '/accessories/hat/2.svg',
    price: 400,
  },
  {
    id: 3,
    name: 'Зеленая шапка',
    type: 'hat',
    imageUrl: '/accessories/hat/3.svg',
    price: 50,
  },
  {
    id: 4,
    name: 'Фермерская шляпа',
    type: 'hat',
    imageUrl: '/accessories/hat/4.svg',
    price: 200,
  },
  {
    id: 5,
    name: 'Розовая шапка',
    type: 'hat',
    imageUrl: '/accessories/hat/5.svg',
    price: 60,
  },
  {
    id: 6,
    name: 'Золотая цепь',
    type: 'necklace',
    imageUrl: '/accessories/necklace/1.svg',
    price: 150,
  },
  {
    id: 7,
    name: 'Красное ожерелье',
    type: 'necklace',
    imageUrl: '/accessories/necklace/2.svg',
    price: 90,
  },
  {
    id: 8,
    name: 'Зеленые бусы',
    type: 'necklace',
    imageUrl: '/accessories/necklace/3.svg',
    price: 90,
  },
  {
    id: 9,
    name: 'Браслет 1',
    type: 'bracelet',
    imageUrl: '/accessories/bracelet/1.svg',
    price: 40,
  },
  {
    id: 10,
    name: 'Золотые часы',
    type: 'bracelet',
    imageUrl: '/accessories/bracelet/2.svg',
    price: 600,
  },
  {
    id: 11,
    name: 'Браслет 2',
    type: 'bracelet',
    imageUrl: '/accessories/bracelet/3.svg',
    price: 40,
  },
  {
    id: 12,
    name: 'Обычные часы',
    type: 'bracelet',
    imageUrl: '/accessories/bracelet/4.svg',
    price: 100,
  },
  {
    id: 13,
    name: 'Браслет 2',
    type: 'bracelet',
    imageUrl: '/accessories/bracelet/5.svg',
    price: 50,
  },
  {
    id: 14,
    name: 'Серебряные часы',
    type: 'bracelet',
    imageUrl: '/accessories/bracelet/6.svg',
    price: 200,
  },
  {
    id: 15,
    name: 'Синие штаны',
    type: 'pants',
    imageUrl: '/accessories/pants/1.svg',
    price: 0,
  },
  {
    id: 16,
    name: 'Зеленые штаны',
    type: 'pants',
    imageUrl: '/accessories/pants/2.svg',
    price: 200,
  },
  {
    id: 17,
    name: 'Розовые штаны',
    type: 'pants',
    imageUrl: '/accessories/pants/3.svg',
    price: 250,
  },
  {
    id: 18,
    name: 'Синие ботинки',
    type: 'boots',
    imageUrl: '/accessories/boots/1.svg',
    price: 170,
  },
  {
    id: 19,
    name: 'Красные мокасины',
    type: 'boots',
    imageUrl: '/accessories/boots/2.svg',
    price: 500,
  },
  {
    id: 20,
    name: 'Зеленые ботинки',
    type: 'boots',
    imageUrl: '/accessories/boots/3.svg',
    price: 170,
  },
  {
    id: 21,
    name: 'Розовые ботинки',
    type: 'boots',
    imageUrl: '/accessories/boots/4.svg',
    price: 190,
  },
]
