import type { Exercise } from '@/types'

export default <Exercise[]>[
  {
    id: 1,
    name: 'Упражнение 1',
    video: null,
    photoUrlList: [],
    description: null,
    difficulty: 'простое',
    sportsItems: ['скакалка'],
    tags: ['ноги'],
    unitsList: ['повторения', 'подходы'],
  },
  {
    id: 2,
    name: 'Упражнение 2',
    video: {
      type: 'iframe',
      url: 'https://www.youtube.com/embed/FqF11YdwxrQ',
    },
    photoUrlList: [],
    description: null,
    difficulty: 'среднее',
    sportsItems: ['штанга'],
    tags: ['бицепс', '12222', '22222', '22223', '42222', '522222222', '6', '7', '8', '0'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 3,
    name: 'Упражнение 3',
    video: null,
    photoUrlList: [
      'https://fitnessclub24.ru/public/images/gallery/section/thumbs/0/2-3-shragi.jpg',
      'https://avatars.dzeninfra.ru/get-zen_doc/1535103/pub_64dbaa4e73f157490e767716_64dbe7e2a9216a3544dafebe/scale_1200',
    ],
    description: null,
    difficulty: 'сложное',
    sportsItems: ['гантели'],
    tags: ['спина'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 4,
    name: 'Случай 4',
    video: {
      type: 'iframe',
      url: 'https://rutube.ru/play/embed/348d394918bfe218476abc144918f909',
    },
    photoUrlList: [
      'https://fitnessclub24.ru/public/images/gallery/section/thumbs/0/2-3-shragi.jpg',
      'https://avatars.dzeninfra.ru/get-zen_doc/1535103/pub_64dbaa4e73f157490e767716_64dbe7e2a9216a3544dafebe/scale_1200',
    ],
    description: 'Описание 2',
    difficulty: 'простое',
    sportsItems: [],
    tags: [],
    unitsList: ['время'],
  },
  {
    id: 5,
    name: 'Жим штанги лёжа',
    video: {
      type: 'video',
      url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-barbell-bench-press-side_KciuhbB.mp4',
    },
    photoUrlList: [],
    description: 'Опустить штангу к груди, затем выжать вверх.',
    difficulty: 'среднее',
    sportsItems: ['штанга', 'скамья'],
    tags: ['грудные', 'трицепс', 'плечи'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 6,
    name: 'Разведение гантелей лёжа',
    video: {
      type: 'video',
      url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-dumbbell-incline-chest-flys-front.mp4',
    },
    photoUrlList: [
      'https://instructorpro.ru/wp-content/uploads/2022/12/%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D1%83%D0%BA-%D0%BB%D0%B5%D0%B6%D0%B0-%D0%92%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5.png',
    ],
    description: 'Развести гантели в стороны, затем вернуть в исходное положение.',
    difficulty: 'среднее',
    sportsItems: ['гантели', 'скамья'],
    tags: ['грудные', 'изоляция'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 7,
    name: 'Подтягивания широким хватом',
    video: {
      type: 'video',
      url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-bodyweight-pullup-front.mp4',
    },
    photoUrlList: [
      'https://avatars.dzeninfra.ru/get-zen_doc/9856080/pub_64c43b5be3f60f18895d0b61_64c44cc4e2687c5d7fe60b36/scale_1200',
    ],
    description: 'Подтянуться к перекладине, затем опуститься.',
    difficulty: 'среднее',
    sportsItems: ['турник'],
    tags: ['спина', 'бицепс'],
    unitsList: ['повторения'],
  },
  {
    id: 8,
    name: 'Тяга гантели в наклоне',
    video: {
      type: 'video',
      url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-kneeling-single-arm-row-front.mp4',
    },
    photoUrlList: [],
    description: 'Упереться одной рукой в скамью, подтянуть гантель к поясу.',
    difficulty: 'среднее',
    sportsItems: ['гантели', 'скамья'],
    tags: ['спина', 'бицепс'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 9,
    name: 'Приседания со штангой',
    video: {
      type: 'video',
      url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-squat-front.mp4',
    },
    photoUrlList: [],
    description: 'Опустить таз вниз, затем подняться.',
    difficulty: 'сложное',
    sportsItems: ['штанга', 'стойка'],
    tags: ['квадрицепсы', 'ягодицы', 'бёдра'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 10,
    name: 'Болгарские сплит-приседы',
    video: {
      type: 'video',
      url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Dumbbells-dumbbell-bulgarian-split-squat-front.mp4',
    },
    photoUrlList: [],
    description: 'Одна нога на скамье, другая — делает выпад вниз.',
    difficulty: 'среднее',
    sportsItems: ['гантели', 'скамья'],
    tags: ['ноги', 'ягодицы'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 11,
    name: 'Ягодичный мостик со штангой',
    video: {
      type: 'video',
      url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-hip-thrust-side.mp4',
    },
    photoUrlList: [],
    description: 'Поднять таз вверх, сжимая ягодицы.',
    difficulty: 'среднее',
    sportsItems: ['штанга', 'скамья'],
    tags: ['ягодицы', 'поясница'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 12,
    name: 'Становая тяга сумо',
    video: null,
    photoUrlList: [],
    description: 'Широкая стойка, подъем штанги с пола.',
    difficulty: 'среднее',
    sportsItems: ['штанга'],
    tags: ['ягодицы', 'ноги', 'поясница'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 13,
    name: 'Армейский жим',
    video: {
      type: 'video',
      url: 'https://media.musclewiki.com/media/uploads/videos/branded/male-Barbell-barbell-overhead-press-side.mp4',
    },
    photoUrlList: [],
    description: null,
    difficulty: 'среднее',
    sportsItems: ['штанга'],
    tags: ['плечи', 'трицепс'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 14,
    name: 'Разведение гантелей в стороны',
    video: null,
    photoUrlList: [],
    description: 'Поднять гантели в стороны до уровня плеч.',
    difficulty: 'простое',
    sportsItems: ['гантели'],
    tags: ['плечи', 'изоляция'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 15,
    name: 'Разгибание рук с гантелями за головой',
    video: null,
    photoUrlList: [],
    description: 'Опустить гантель за голову, затем разогнуть руки.',
    difficulty: 'среднее',
    sportsItems: ['гантели'],
    tags: ['трицепс'],
    unitsList: ['повторения', 'вес'],
  },
  {
    id: 16,
    name: 'Бег',
    video: null,
    photoUrlList: [],
    description: null,
    difficulty: 'простое',
    sportsItems: [],
    tags: ['ноги'],
    unitsList: ['время'],
  },
]
