/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditExerciseDialog: typeof import('./src/components/EditExerciseDialog.vue')['default']
    EditWorkoutAddedExercise: typeof import('./src/components/EditWorkoutAddedExercise.vue')['default']
    EditWorkoutDialog: typeof import('./src/components/EditWorkoutDialog.vue')['default']
    ExerciseCard: typeof import('./src/components/ExerciseCard.vue')['default']
    ExerciseCardInfo: typeof import('./src/components/ExerciseCardInfo.vue')['default']
    ExercisesListFilters: typeof import('./src/components/ExercisesListFilters.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Galleria: typeof import('primevue/galleria')['default']
    GoalInput: typeof import('./src/components/GoalInput.vue')['default']
    IframeLoader: typeof import('./src/components/IframeLoader.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    ShopItemTypedList: typeof import('./src/components/ShopItemTypedList.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    VirtualScroller: typeof import('primevue/virtualscroller')['default']
  }
}
